SmartCityResarvation/TheEye/Controllers/CarParkController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUL.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class CarParkController : Controller
    {
        private ICarParkService _carParkService;
        public CarParkController(ICarParkService carkParkService)
        {
            _carParkService = carkParkService;
        }

        [Ignore]
        [Route("Otopark")]
        public ActionResult CarPark()
        {
            var model = _carParkService.GetAll();
            return View(model);
        }

        [Route("Admin/OtoparkBilgiGirisi/{companyId}")]
        public ActionResult CarParkAdd(int companyId)
        {
            var modal = new CarPark
            {
                CarParkDisabled = false,
                CarParkMarket = false,
                CarParkMax = 0,
                CarParkNull = 0,
                CarParkTire = false,
                CarParkWashing = false,
                CompanyId = companyId
            };
            _carParkService.Add(modal);
            return View("CarParkOparation", modal);
        }

        [Route("Admin/OtoparkGuncelle/{id}")]
        public ActionResult CarParkOparation(int id)
        {
            var modal = _carParkService.Get(id);
            return View(modal);
        }

        public ActionResult CarParkOptionsCrud(CarPark carPark)
        {
            _carParkService.Update(carPark);
            return RedirectToAction("CarParkGetList");
        }

        [Route("Admin/OtoparkListesi")]
        public ActionResult CarParkGetList()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            List<CarPark> model = _carParkService.GetAll().Where(x => x.Company.UserId == userId).ToList();
            return View(model);
        }
    }
}

SmartCityResarvation/TheEye/Controllers/PetrolStationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUL.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class PetrolStationController : Controller
    {
        public IPetrolStationService PetrolStationService;
        public PetrolStationController(IPetrolStationService petrolStationService)
        {
            PetrolStationService = petrolStationService;
        }

        [Ignore]
        [Route("PetrolOfisi")]
        public ActionResult PetrolStation()
        {
            //var session = HttpContext.Session;
            //if (session != null)
            //{
            //    HttpContext.Session.TryGetValue("token", out var result);
            //    if (result != null)
            //        return View();
            //}
            List<PetrolStation> model = PetrolStationService.GetAll();
            return View(model);
        }

        [Route("Admin/PetrolOfisiListesi")]
        public ActionResult PetrolStationGetList()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            List<PetrolStation> model = PetrolStationService.GetAll().Where(x => x.Company.UserId == userId).ToList();
            return View(model);
        }

        [Route("Admin/PetrolOfisiBilgiGirisi/{companyId}")]
        public ActionResult PetrolStationAdd(int companyId)
        {
            var modal = new PetrolStation
            {
                PetrolMarkets = false,
                PetrolTire = false,
                PetrolWashing = false,
                CompanyId = Convert.ToInt32(HttpContext.Session.GetString("UserId"))
            };
            PetrolStationService.Add(modal);
            return View("PetrolStationOparation", modal);
        }

        [Route("Admin/PetrolOfisiGuncelle/{id}")]
        public ActionResult PetrolStationOparation(int id)
        {
            var modal = PetrolStationService.Get(id);
            return View(modal);
        }

        public ActionResult PetrolStationOparationCrud(PetrolStation petrolStation)
        {
            PetrolStationService.Update(petrolStation);
            return RedirectToAction("PetrolStationGetList");
        }
    }
}

SmartCityResarvation/TheEye/Controllers/PharmacyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using TheEye.Business.Abstract;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUL.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class PharmacyController : Controller
    {
        private ICompanyService _companyService;
        public PharmacyController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        [Ignore]
        [Route("Eczane")]
        public ActionResult Pharmacy()
        {
            var model = _companyService.GetAll().Where(x => x.CompanyType == 2).ToList();
            return View(model);
        }

        [Route("Admin/EczaneListesi")]
        public ActionResult PharmacyGetList()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            var model = _companyService.GetAll().Where(x => x.UserId == userId).ToList();
            return View(model);
        }
    }
}

SmartCityResarvation/TheEye/Views/Shared/AdminSite/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Admin Paneli</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/css/now-ui-dashboard.css?v=1.5.0" rel="stylesheet" />

</head>

<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="orange">
            <div class="logo">
                <a href="#" class="simple-text logo-normal">EyeOn</a>
            </div>
            <div class="sidebar-wrapper" id="sidebar-wrapper">
                <ul class="nav">
                    <li class="active ">
                        <a href="/Admin/FirmaKayit">
                            <i class="fas fa-building"></i>
                            <p>Firma Kayıt</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="CarPark" asp-action="CarParkGetList">
                            <i class="fas fa-car"></i>
                            <p>OTOPARK</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="PetrolStation" asp-action="PetrolStationGetList">
                            <i class="fas fa-gas-pump"></i>
                            <p>PETROL İSTASYONU</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Pharmacy" asp-action="PharmacyGetList">
                            <i class="fas fa-prescription-bottle-alt"></i>
                            <p>ECZANE</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel" id="main-panel">
            <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#pablo">@ViewBag.Title</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-user"></i>
                                    <p>
                                        <span class="d-lg-none d-md-block">Hesap</span>
                                    </p>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <a asp-controller="Account" asp-action="MyAccount" class="dropdown-item">Hesabım</a>
                                    <a asp-controller="Account" asp-action="LogOff" class="dropdown-item">Çıkış Yap</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="panel-header panel-header-sm">
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/js/now-ui-dashboard.min.js?v=1.5.0" type="text/javascript"></script>
</body>
</html>