SmartCityResarvation/TheEye/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Options;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Filters;
using TheEye.WebUl.Models;

namespace TheEye.WebUl.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class CompanyController : Controller
    {
        private ICompanyService _companyService;
        private IHostingEnvironment _environment;
        private readonly ServiceModal _serviceModal;
        public CompanyController(ICompanyService companyService, IHostingEnvironment enviroment, IOptions<ServiceModal> servicesOptions)
        {
            _serviceModal = servicesOptions.Value;
            _companyService = companyService;
            _environment = enviroment ?? throw new ArgumentNullException(nameof(enviroment));
        }

        [Route("Admin/FirmaKayit")]
        public ActionResult CompanyAdd()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CompanyControlAdd(CompanyViewModal companyViewModal)
        {
            string filenameadd = DateTime.Now.ToString(CultureInfo.InvariantCulture).Replace(" ", "_").Replace(":", "_").Replace(".", "_").Replace(" ", "_").Replace("/", "_").Replace("\\", "_");
            string images = Path.Combine(_environment.WebRootPath, "images/CompanyImages");
            string imagesPath = filenameadd + companyViewModal.ImageFile.FileName;

            if (companyViewModal.ImageFile.Length > 0)
            {
                await using (var fileStream = new FileStream(Path.Combine(images,
                    imagesPath), FileMode.Create))
                {
                    await companyViewModal.ImageFile.CopyToAsync(fileStream);
                }
            }
            companyViewModal.CompanyImage = imagesPath;
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync(string.Format("http://{0}:{1}/CompanyControlTax?TaxNo={2}&Name={3}",_serviceModal.IpAddress, _serviceModal.Port,  companyViewModal.CompanyTaxNo, companyViewModal.CompanyName));
                var model = JsonConvert.DeserializeObject<IEnumerable<ServiceCompanyControl>>(
                    response.Content.ReadAsStringAsync().Result);
                int companyType = 0;
                if (model != null)
                    foreach (var item in model)
                    {
                        companyType = item.CompanyType;
                    }
                Company company = new Company
                {
                    CompanyName = companyViewModal.CompanyName,
                    CompanyAdress = companyViewModal.CompanyAdress,
                    CompanyCity = companyViewModal.CompanyCity,
                    CompanyDistrict = companyViewModal.CompanyDistrict,
                    CompanyMail = companyViewModal.CompanyMail,
                    CompanyPhone = companyViewModal.CompanyPhone,
                    CompanyType = companyType,
                    UserId = Convert.ToInt32(HttpContext.Session.GetString("UserId"))
                };
                _companyService.Add(company);
                company = _companyService.GetAll().OrderByDescending(x => x.CompanyId).FirstOrDefault();

                if (companyType == 0)
                    return RedirectToAction("CarParkAdd", "CarPark", new { companyId = company?.CompanyId });
                else if (companyType == 1)
                    return RedirectToAction("PetrolStationAdd", "PetrolStation", new { companyId = company?.CompanyId });
                else
                    return RedirectToAction("PharmacyGetList", "Pharmacy");
            }
        }

        [Route("Admin/FirmaGuncelleme/{id}")]
        public ActionResult CompanyUpdate(int id)
        {
            var modal = _companyService.Get(id);
            return View(modal);
        }

        public ActionResult CompanyDelete(int id)
        {
            var modal = _companyService.Get(id);
            _companyService.Delete(modal);
            TempData.Add("Message", "Silme işleminiz başarılı bir şekilde gerçekleştirirldi.");
            return RedirectToAction("Admin", "Account");
        }
    }
}

SmartCityResarvation/TheEye/Controllers/MedicineController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUl.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class MedicineController : Controller
    {
        private IMedicineService _medicineService;

        public MedicineController(IMedicineService medicineService)
        {
            _medicineService = medicineService;
        }

        [Ignore]
        public ActionResult Medicine()
        {
            var modal = _medicineService.GetAll();
            return View(modal);
        }
        [Route("Admin/IlacListesi/{PharmacyId}")]
        public ActionResult MedicineGetList(int pharmacyId)
        {
            var modal = _medicineService.GetAll().Where(x =>x.CompanyId == pharmacyId);
            return View(modal);
        }

        [Route("Admin/IlacEkleme/{PharmacyId}")]
        [Route("Admin/IlacGuncelle/{id}")]
        public ActionResult MedicineOparation(int id = 0, int pharmacyId = 0)
        {
            var modal = new Medicine
            {
                CompanyId = pharmacyId
            };
            if (id == 0)
                return View(modal);
            modal = _medicineService.Get(id);
            return View(modal);
        }

        public ActionResult MedicineOparationCrud(Medicine medicine)
        {
            if (medicine.MedicineId == 0)
                _medicineService.Add(medicine);
            else
                _medicineService.Update(medicine);
            return RedirectToAction("PharmacyGetList","Pharmacy");
        }

        public ActionResult MedicineDelete(int id)
        {
            Medicine medicine = _medicineService.Get(id);
            _medicineService.Delete(medicine);
            TempData.Add("Message", "Silme işleminiz başarılı bir şekilde gerçekleştirirldi.");
            return RedirectToAction("PharmacyGetList","Pharmacy");
        }
    }
}

SmartCityResarvation/TheEye/Controllers/PharmacyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using TheEye.Business.Abstract;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUL.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class PharmacyController : Controller
    {
        private ICompanyService _companyService;
        public PharmacyController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        [Ignore]
        [Route("Eczane")]
        public ActionResult Pharmacy()
        {
            var model = _companyService.GetAll().Where(x => x.CompanyType == 2).ToList();
            return View(model);
        }

        [Route("Admin/EczaneListesi")]
        public ActionResult PharmacyGetList()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            var model = _companyService.GetAll().Where(x => x.UserId == userId).ToList();
            return View(model);
        }
    }
}

SmartCityResarvation/TheEye/Views/Pharmacy/Pharmacy.cshtml
@model List<TheEye.Entities.Concrete.Company>
@{
    ViewBag.Title = "Eczane Listesi";
}

@await Html.PartialAsync("MainSite/_Banner")
<div class="container">
    <br />
    <div class="input-group mb-3">
        <input id="input-text" type="text" class="form-control" placeholder="Arama Yap..." aria-label="Recipient's username" aria-describedby="button-addon2">
    </div>
    @foreach (var item in Model)
    {
        <div class="card mb-3" style="max-width: 1540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="~/images/Pharmacist.jpg"
                         class="card-img"
                         height="100%"
                         alt="..." />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">@item.CompanyName</h5>
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">İl</th>
                                            <th scope="col">İlçe</th>
                                            <th scope="col">Telefon</th>
                                            <th scope="col">E-mail</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>@item.CompanyCity</td>
                                            <td>@item.CompanyDistrict</td>
                                            <td>@item.CompanyPhone</td>
                                            <td>@item.CompanyMail</td>
                                        </tr>
                                    </tbody>
                                    <thead>
                                    <tr>
                                        <th>Adres</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>@item.CompanyAdress</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

SmartCityResarvation/TheEye/Views/Pharmacy/PharmacyGetList.cshtml
@model System.Collections.Generic.List<TheEye.Entities.Concrete.Company>
@{
    ViewBag.Title = "Eczane Listesi";
    Layout = "AdminSite/_AdminLayout";
}

<div class="card-header">
    <h4 class="card-title">Eczane Listesi</h4>
</div>
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead class="text-primary">
                <tr>
                    <th>Eczane Adı</th>
                    <th>Eczane Telefon Numarası</th>
                    <th>Eczane Mail Adresi</th>
                    <th>Şehir</th>
                    <th>Bölge</th>
                    <th>Kapanış Saati</th>
                    <th>Eczane Adresi</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.CompanyName</td>
                    <td>@item.CompanyPhone</td>
                    <td>@item.CompanyMail</td>
                    <td>@item.CompanyCity</td>
                    <td>@item.CompanyDistrict</td>
                    <td>@item.CompanyTime</td>
                    <td>@item.CompanyAdress</td>
                    <td>
                        <a asp-controller="Medicine" asp-action="MedicineOparation" asp-route-pharmacyId="@item.CompanyId" class="btn btn-success">İlaç Ekle</a>
                    </td>
                    <td>
                        <a asp-controller="Medicine" asp-action="MedicineGetList" asp-route-PharmacyId="@item.CompanyId" class="btn btn-success">İlaç Listesi</a>
                    </td>
                    <td>
                        <a asp-controller="Company" asp-action="CompanyUpdate" asp-route-id="@item.CompanyId" class="btn btn-success">Firma Bilgi Güncelle</a>
                    </td>
                    <td>
                        <a asp-controller="Company" asp-action="CompanyDelete" asp-route-id="@item.CompanyId" class="btn btn-danger text-light">Sil </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SmartCityResarvation/TheEye/Views/Pharmacy/PharmacyOparation.cshtml
@model TheEye.Entities.Concrete.Medicine

@{
    ViewBag.Title = "Eczane İşlemleri";
    Layout = "AdminSite/_AdminLayout";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="title"> Eczane Bilgisi</h5>
                </div>
                <div class="card-body">
                    <form asp-controller="Pharmacy" asp-action="">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Company.CompanyName">Eczane Adı:</label>
                                    <input  asp-for="Company.CompanyName" type="text" class="form-control" placeholder="Eczane Adı" value="" required="" name="CompanyName">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label  asp-for="Company.CompanyMail">Eczane Mail Adresi:</label>
                                    <input  asp-for="Company.CompanyMail"type="text" class="form-control" placeholder="Eczane Mail Adresi" value="" name="CompanyMail"
                                           required="">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Company.CompanyPhone">Eczane Telefon Numarası:</label>
                                    <input asp-for="Company.CompanyPhone" type="text" class="form-control" placeholder="Eczane Telefon Numarası" name="CompanyPhone"
                                           required="">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="Company.CompanyCity">Şehir:</label>
                                    <input asp-for="Company.CompanyCity" type="text" class="form-control" placeholder="Şehir" value="" name="CompanyCity"
                                           required="">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="Company.CompanyDistrict">Bölge:</label>
                                    <input asp-for="Company.CompanyDistrict" type="text" class="form-control" placeholder="Bölge" value="" name="CompanyDistrict"
                                           required="">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="Company.CompanyTime">Kapanış Saati:</label>
                                    <input asp-for="Company.CompanyTime" type="text" class="form-control" placeholder="Kapanış Saati" value="" name="
                                           CompanyTime"
                                           required="">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Company.CompanyAdress">Eczane Adresi:</label>
                                    <input asp-for="Company.CompanyAdress" type="text" class="form-control" placeholder="Eczane Adresi" value="" name="CompanyAdress"
                                           required="">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4"></div>
                            <div class="col-md-4"></div>
                            <input type="hidden" asp-for="CompanyId"/>
                            <div class="col-md-4">
                                <button class="btn btn-primary btn-block" value="PharmacyOparations"> Katılım İsteği Gönder </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>