SmartCityResarvation/TheEye/Controllers/CarParkController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUL.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class CarParkController : Controller
    {
        private ICarParkService _carParkService;
        public CarParkController(ICarParkService carkParkService)
        {
            _carParkService = carkParkService;
        }

        [Ignore]
        [Route("Otopark")]
        public ActionResult CarPark()
        {
            var model = _carParkService.GetAll();
            return View(model);
        }

        [Route("Admin/OtoparkBilgiGirisi/{companyId}")]
        public ActionResult CarParkAdd(int companyId)
        {
            var modal = new CarPark
            {
                CarParkDisabled = false,
                CarParkMarket = false,
                CarParkMax = 0,
                CarParkNull = 0,
                CarParkTire = false,
                CarParkWashing = false,
                CompanyId = companyId
            };
            _carParkService.Add(modal);
            return View("CarParkOparation", modal);
        }

        [Route("Admin/OtoparkGuncelle/{id}")]
        public ActionResult CarParkOparation(int id)
        {
            var modal = _carParkService.Get(id);
            return View(modal);
        }

        public ActionResult CarParkOptionsCrud(CarPark carPark)
        {
            _carParkService.Update(carPark);
            return RedirectToAction("CarParkGetList");
        }

        [Route("Admin/OtoparkListesi")]
        public ActionResult CarParkGetList()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            List<CarPark> model = _carParkService.GetAll().Where(x => x.Company.UserId == userId).ToList();
            return View(model);
        }
    }
}

SmartCityResarvation/TheEye/Controllers/MedicineController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUl.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class MedicineController : Controller
    {
        private IMedicineService _medicineService;

        public MedicineController(IMedicineService medicineService)
        {
            _medicineService = medicineService;
        }

        [Ignore]
        public ActionResult Medicine()
        {
            var modal = _medicineService.GetAll();
            return View(modal);
        }
        [Route("Admin/IlacListesi/{PharmacyId}")]
        public ActionResult MedicineGetList(int pharmacyId)
        {
            var modal = _medicineService.GetAll().Where(x =>x.CompanyId == pharmacyId);
            return View(modal);
        }

        [Route("Admin/IlacEkleme/{PharmacyId}")]
        [Route("Admin/IlacGuncelle/{id}")]
        public ActionResult MedicineOparation(int id = 0, int pharmacyId = 0)
        {
            var modal = new Medicine
            {
                CompanyId = pharmacyId
            };
            if (id == 0)
                return View(modal);
            modal = _medicineService.Get(id);
            return View(modal);
        }

        public ActionResult MedicineOparationCrud(Medicine medicine)
        {
            if (medicine.MedicineId == 0)
                _medicineService.Add(medicine);
            else
                _medicineService.Update(medicine);
            return RedirectToAction("PharmacyGetList","Pharmacy");
        }

        public ActionResult MedicineDelete(int id)
        {
            Medicine medicine = _medicineService.Get(id);
            _medicineService.Delete(medicine);
            TempData.Add("Message", "Silme işleminiz başarılı bir şekilde gerçekleştirirldi.");
            return RedirectToAction("PharmacyGetList","Pharmacy");
        }
    }
}

SmartCityResarvation/TheEye/Controllers/PetrolStationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TheEye.Business.Abstract;
using TheEye.Entities.Concrete;
using TheEye.WebUl.Atributes;
using TheEye.WebUl.Filters;

namespace TheEye.WebUL.Controllers
{
    [ServiceFilter(typeof(LoginFilter))]
    public class PetrolStationController : Controller
    {
        public IPetrolStationService PetrolStationService;
        public PetrolStationController(IPetrolStationService petrolStationService)
        {
            PetrolStationService = petrolStationService;
        }

        [Ignore]
        [Route("PetrolOfisi")]
        public ActionResult PetrolStation()
        {
            //var session = HttpContext.Session;
            //if (session != null)
            //{
            //    HttpContext.Session.TryGetValue("token", out var result);
            //    if (result != null)
            //        return View();
            //}
            List<PetrolStation> model = PetrolStationService.GetAll();
            return View(model);
        }

        [Route("Admin/PetrolOfisiListesi")]
        public ActionResult PetrolStationGetList()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("UserId"));
            List<PetrolStation> model = PetrolStationService.GetAll().Where(x => x.Company.UserId == userId).ToList();
            return View(model);
        }

        [Route("Admin/PetrolOfisiBilgiGirisi/{companyId}")]
        public ActionResult PetrolStationAdd(int companyId)
        {
            var modal = new PetrolStation
            {
                PetrolMarkets = false,
                PetrolTire = false,
                PetrolWashing = false,
                CompanyId = Convert.ToInt32(HttpContext.Session.GetString("UserId"))
            };
            PetrolStationService.Add(modal);
            return View("PetrolStationOparation", modal);
        }

        [Route("Admin/PetrolOfisiGuncelle/{id}")]
        public ActionResult PetrolStationOparation(int id)
        {
            var modal = PetrolStationService.Get(id);
            return View(modal);
        }

        public ActionResult PetrolStationOparationCrud(PetrolStation petrolStation)
        {
            PetrolStationService.Update(petrolStation);
            return RedirectToAction("PetrolStationGetList");
        }
    }
}

SmartCityResarvation/TheEye/Views/Shared/MainSite/_Banner.cshtml
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-4">
                <h1>
                    @{ var title = (ViewBag.Title.ToString()).ToUpper();}
                    @title
                            </h1>
            </div>
        </div>
    </div>
</div>

SmartCityResarvation/TheEye/Views/Shared/MainSite/_Footer.cshtml
<footer>
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="mt-5 col-12 text-center">
                    <p style="padding: 5px">EyeON Proje geliştirme grubu olarak günümüzde yükse ilgi gören ve gelecekte 
                    tamamen yer edineceğini düşündüğümüz akıllı şehir sistemleri geliştirmekteyiz.</p>
                    <p>Manisa Celal Bayar Üniversitesi Hasan Ferdi Turgutlu Teknoloji Fakültesi</p>
                </div>
                @*<div class="mt-5 col-6 text-center">
                    <h1>HAZIRLAYANLAR</h1>
                    <ul class="list-unstyled">
                        <li style="padding: 5px"><i class="fa fa-angle-right" aria-hidden="true"></i> İsmet KİZGİN</li>
                        <li style="padding: 5px"><i class="fa fa-angle-right" aria-hidden="true"></i> Alihan AKÇAM</li>
                        <li style="padding: 5px"><i class="fa fa-angle-right" aria-hidden="true"></i> İrem ÇELİKBİLEK</li>
                        <li style="padding: 5px"><i class="fa fa-angle-right" aria-hidden="true"></i> Kadir Can KARADEMİR</li>
                    </ul>
                </div>*@
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <p>powered by &copy; EyeON </p>
                </div>
            </div>
        </div>
    </div>
</footer>

SmartCityResarvation/TheEye/Views/Shared/MainSite/_Header.cshtml
<header>
    <div class="content_header">
        <div class="container">
            <div class="row text-muted">
                <div class="col-md-6 align-md-center align-sm-center">
                    <i class="fa fa-phone"></i>
                    <span class="mobile-phone">
                        <a class="text-muted" href="tel:+905393834430"> 539 383 44 30</a>
                    </span>

                    <span class="desktop-phone"> 539 383 44 30</span>
                </div>

                <div class="col-md-6 align-md-center align-sm-center">
                    <i class="fas fa-envelope"></i> <a class="text-muted" href="mailto:ismetkizgin@hotmail.com">ismetkizgin@hotmail.com</a>
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: transparent;">
        <div class="container">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse px-3" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a asp-controller="Home" asp-action="index" class="nav-item nav-link">Anasayfa</a>
                    <a asp-controller="CarPark" asp-action="CarPark" class="nav-item nav-link pl-3">Otopark</a>
                    <a asp-controller="PetrolStation" asp-action="PetrolStation" class="nav-item nav-link pl-3">Petrol Ofisi</a>
                    <li class="nav-item dropdown px-3">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Eczane
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="Pharmacy" asp-action="Pharmacy">Eczaneler</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Medicine" asp-action="Medicine">İlaçlar</a>
                        </div>
                    </li>
                    <a asp-controller="Home" asp-action="About" class="nav-item nav-link pl-3">Hakkımızda</a>
                </div>
            </div>
            <form class="form-inline my-2 my-lg-0" method="post">
                <a asp-controller="Account" asp-action="Login" type="button" class="btn btn-success btn-round btn-ouutline-success">Giriş Yap</a>
            </form>
        </div>
    </nav>

</header>

SmartCityResarvation/TheEye/Views/Shared/MainSite/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title | The Eye</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />


</head>
<body>

    @await Html.PartialAsync("MainSite/_Header")
    @RenderBody()
    @await Html.PartialAsync("MainSite/_Footer")

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/loginform.js"></script>
    <script src="~/js/search.js"></script>

    @if (TempData["stateLogin"] != null)
    {
        <script>
            $(document).ready(function () {
                $("#loginModal").modal('show');
            });
        </script>
    }
</body>
</html>